version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 20
  reviewers:
  - agusID
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.4.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: svelte-loader
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: svelte
    versions:
    - 3.31.2
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.35.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
